name: photoacoustic-py38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - h5py
  - scikit-image
  - tensorflow
  - astropy
  - mkl_fft
  - pip
  - pip:
      - git+https://github.com/berkanlafci/pyoat.git
      - ipython
      - jupyter
      - sewar
      - pyfftw