name: photoacoustic-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.4
  - scipy=1.9.1
  - matplotlib
  - h5py
  - scikit-image
  - tensorflow>=2.12
  - astropy
  - mkl_fft
  - pip
  - cudatoolkit=11.8  # CUDA for GPU acceleration (matches PyTorch and TensorFlow)
  - pip:
      - git+https://github.com/berkanlafci/pyoat.git
      - ipython
      - jupyter
      - sewar
      - pyfftw
      - read-roi
      - tqdm
      - opencv-python
      - image-similarity-measures
      - brisque
      - libsvm-official
      - torch 
      - torchvision 
      - torchaudio
      - joblib
      - piq