name: photoacoustic-env
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - h5py
  - scikit-image
  - tensorflow
  - pip
  - pip:
      - git+https://github.com/berkanlafci/pyoat.git
      - ipython
      - jupyter